# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelTui < Formula
  desc "Terminal OpenTelemetry viewer (fork rebuild of ymtdzzz/otel-tui, Apache-2.0)"
  homepage "https://github.com/ymtdzzz/otel-tui"
  version "0.7.4-n4m3z.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/N4M3Z/otel-tui/releases/download/v0.7.4-n4m3z.1/otel-tui_Darwin_x86_64.tar.gz"
      sha256 "ffd92a2171e38b6659e56936e596aeecece791c40cbcda820ba60b8773292567"

      define_method(:install) do
        bin.install "otel-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/N4M3Z/otel-tui/releases/download/v0.7.4-n4m3z.1/otel-tui_Darwin_arm64.tar.gz"
      sha256 "43b52d7a8cf4ff927888c6c64c96118db094999564612fbe39401221119aa3b4"

      define_method(:install) do
        bin.install "otel-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/N4M3Z/otel-tui/releases/download/v0.7.4-n4m3z.1/otel-tui_Linux_x86_64.tar.gz"
      sha256 "ad2d95524a26d1e20fa5003fa94623c7e4a871872f7435619b072d06352130dd"
      define_method(:install) do
        bin.install "otel-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/N4M3Z/otel-tui/releases/download/v0.7.4-n4m3z.1/otel-tui_Linux_arm64.tar.gz"
      sha256 "7d07eb4ea498514b29646d7c8e721c106babbbc413d56ea9f65980f8bdf4b16c"
      define_method(:install) do
        bin.install "otel-tui"
      end
    end
  end

  def caveats
    <<~EOS
      Rebuild of upstream ymtdzzz/otel-tui at a stable commit past 0.7.3; no code changes.
    EOS
  end
end
